- name: Ping from Mikrotik Router
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping IP 10.21.24.12 từ thiết bị Mikrotik
      community.network.routeros_command:
        commands:
          - /ping 10.21.24.12 count=5
      vars:
        ansible_connection: ssh
        ansible_user: haiTT
        ansible_password: Hai123456@
        ansible_network_os: routeros
