- name: Kiểm tra kết nối SSH tới Mikrotik
  hosts: A1
  gather_facts: no
  tasks:
    - name: Đợi kết nối qua SSH
      ansible.builtin.wait_for_connection:

    - name: Lấy hostname Mikrotik
      ansible.netcommon.cli_command:
        command: /system identity print
      register: output

    - name: In ra kết quả
      debug:
        var: output.stdout_lines
