- name: Configure Mikrotik Router
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure SNMP is enabled on Mikrotik
      community.network.routeros_command:
        commands:
          - /snmp set enabled=yes
          - /snmp community set [ find name=public ] addresses=0.0.0.0/0
      vars:
        ansible_network_os: routeros
        ansible_connection: network_cli
        ansible_user: haiTT
        ansible_password: Hai123456@
