- name: Ping Mikrotik Router
  hosts: all
  gather_facts: no
  tasks:
    - name: Test connectivity to Mikrotik
      ansible.builtin.ping:
      vars:
        ansible_connection: ssh  # Sử dụng SSH thay vì network_cli
        ansible_user: haiTT
        ansible_password: Hai123456@
        ansible_network_os: routeros  # Tùy chọn, giữ nếu cần
