- name: Ping Mikrotik from Ubuntu server
  hosts: ubuntu-server
  gather_facts: no
  tasks:
    - name: Ping Mikrotik router at 10.20.25.19
      ansible.builtin.shell: ping -c 4 10.20.25.19
      register: ping_result

    - name: Show ping result
      debug:
        var: ping_result.stdout_lines
