- name: Verify SSH to Mikrotik Router
  hosts: all
  gather_facts: no
  tasks:
    - name: Verify connectivity to Mikrotik
      ansible.netcommon.net_ping:
      vars:
        ansible_connection: network_cli
        ansible_network_os: routeros
        ansible_user: haiTT
        ansible_password: Hai123456@
      register: ping_result
      failed_when: ping_result.failed or ping_result.unreachable
