- name: SSH vào thiết bị Mikrotik và ping đến 10.21.24.12
  hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Ping IP 10.21.24.12 từ thiết bị Mikrotik
      ansible.netcommon.cli_command:
        command: ping 10.21.24.12
      register: ping_output

    - name: Hiển thị kết quả ping
      debug:
        var: ping_output.stdout_lines
