- name: SSH vào Mikrotik và ping IP
  hosts: mikrotik
  gather_facts: no
  collections:
    - ansible.netcommon
  tasks:
    - name: Ping IP 10.21.24.12 từ thiết bị Mikrotik
      cli_command:
        command: /tool ping 10.21.24.12 count=4
      register: ping_output

    - name: Hiển thị kết quả ping
      debug:
        var: ping_output.stdout_lines
