- name: Verify SSH to Mikrotik (Read-only check)
  hosts: all
  gather_facts: no
  collections:
    - community.routeros

  tasks:
    - name: Show system identity (hostname)
      routeros_command:
        commands:
          - /system identity print
      register: identity_result

    - name: Show result
      debug:
        var: identity_result.stdout_lines
