- name: Verify SSH and Manage Mikrotik Router
  hosts: all
  gather_facts: no
  collections:
    - community.network
  tasks:
    - name: Verify connectivity to Mikrotik
      community.routeros.routeros_command:
        commands:
          - /system identity print
      register: conn_result
      failed_when: conn_result.failed or 'error' in conn_result.stdout
