- name: Ping test from Mikrotik
  hosts: all
  gather_facts: no
  collections:
    - community.routeros

  tasks:
    - name: Ping 10.21.24.12 from Mikrotik
      routeros_command:
        commands:
          - /ping 10.21.24.12 count=4
      register: ping_result

    - name: Show ping result
      debug:
        var: ping_result.stdout_lines
