- name: Verify SSH to Mikrotik Router
  hosts: all
  gather_facts: no
  tasks:
    - name: Verify connectivity to Mikrotik
      community.network.routeros_command:
        commands:
          - /system identity print
      register: conn_result
      failed_when: conn_result.failed or 'error' in conn_result.stdout
