- name: Ping Mikrotik Router
  hosts: all
  gather_facts: no
  tasks:
    - name: Test connectivity to Mikrotik
      ansible.builtin.ping:
      vars:
        ansible_network_os: routeros
        ansible_connection: network_cli
        ansible_user: haiTT
        ansible_password: Hai123456@
