- name: Ping A1 via SNMP
  hosts: localhost
  gather_facts: no
  tasks:
    - name: SNMP check A1
      ansible.builtin.command: snmpwalk -v2c -c public 10.20.25.19
      register: snmp_result

    - name: Show SNMP result
      debug:
        var: snmp_result.stdout_lines
