- name: Verify SSH to Mikrotik Router
  hosts: all
  gather_facts: no
  tasks:
    - name: Verify SSH connectivity to Mikrotik
      ansible.builtin.wait_for_connection:
      register: ssh_result
      failed_when: ssh_result.failed or ssh_result.unreachable
