- name: Lấy danh sách VM từ VMware vCenter/ESXi
  hosts: vcenter_phenikaa  # Không dùng localhost nữa
  gather_facts: false
  tasks:
    - name: Lấy danh sách các máy ảo
      community.vmware.vmware_vm_info:
        hostname: "{{ vmware_host }}"
        username: "{{ vmware_user }}"
        password: "{{ vmware_password }}"
        validate_certs: false
      register: vm_info

    - name: In kết quả
      debug:
        var: vm_info.virtual_machines
