---
- name: Gather VMware Datacenter Info
  hosts: 10.20.4.9
  gather_facts: no
  tasks:
    - name: Get datacenter information
      community.vmware.vmware_datacenter_info:
        hostname: "10.20.4.9"
        username: "zabbix"
        password: "Phenikaa@#2025*!"
        validate_certs: no
      register: datacenter_info
    - name: Display datacenter info
      debug:
        msg: "{{ datacenter_info.datacenters | default([]) }}"
