- name: Lấy danh sách VM từ VMware vCenter/ESXi
  hosts: 10.20.4.9
  gather_facts: false
  tasks:
    - name: Lấy danh sách các máy ảo
      community.vmware.vmware_vm_info:
        hostname: "{{ vmware_host }}"
        username: "{{ vmware_user }}"
        password: "{{ vmware_password }}"
        validate_certs: "{{ vmware_validate_certs }}"
      register: vm_info

    - name: In danh sách VM (tên, IP, MAC)
      debug:
        msg: |
          Tên máy ảo: {{ item.guest_name }}
          IP: {{ item.ip_address | default('N/A') }}
          MAC: {{ item.mac_address | join(', ') if item.mac_address is defined else 'N/A' }}
      loop: "{{ vm_info.virtual_machines }}"
