---
- name: Lấy danh sách VM từ VMware vCenter/ESXi
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  tasks:
    - name: Lấy danh sách các máy ảo
      vmware_vm_info:
        hostname: "{{ vmware_host }}"
        username: "{{ vmware_user }}"
        password: "{{ vmware_password }}"
        validate_certs: no
      register: vm_list

    - name: In danh sách máy ảo
      debug:
        var: vm_list.virtual_machines
