# ping-from-ubuntu.yml
---
- name: Ping 10.21.24.12 từ host ubuntu (inventory)
  hosts: ubuntu
  gather_facts: false
  become: false

  tasks:
    - name: ICMP ping
      ansible.builtin.command: "/usr/bin/ping -c 4 -W 2 10.21.24.12"
      register: ping_out
      changed_when: false
      failed_when: ping_out.rc != 0

    - name: In kết quả từng dòng
      ansible.builtin.debug:
        msg: "{{ ping_out.stdout_lines }}"
