# tcp-check-10.21.24.12.yml
---
- name: TCP check tới 10.21.24.12:22 từ AWX/Controller
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Đợi cổng 22 mở (timeout 3s)
      ansible.builtin.wait_for:
        host: 10.21.24.12
        port: 22
        timeout: 3
      register: tcp_ok

    - name: Xác nhận reachable
      ansible.builtin.assert:
        that: tcp_ok.elapsed is defined
        success_msg: "OK: 10.21.24.12 reachable qua TCP/22"
        fail_msg: "Không reach được TCP/22"
