- name: Shutdown Ubuntu Server (fire-and-forget)
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo

  tasks:
    - name: Trigger shutdown now
      ansible.builtin.command: /sbin/shutdown -h now "Triggered by AWX"
      async: 1
      poll: 0
      changed_when: true
