# stop-zabbix-min.yml
---
- name: Stop Zabbix & verify
  hosts: all
  become: true
  gather_facts: false

  vars:
    zabbix_services: ["zabbix-server"]   # thêm "zabbix-agent2" nếu cần

  tasks:
    - name: Stop services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      loop: "{{ zabbix_services }}"

    - name: Read service states
      ansible.builtin.service_facts:

    - name: Ensure services are stopped
      ansible.builtin.assert:
        that:
          - "ansible_facts.services['{{ item }}.service'].state == 'stopped'"
        fail_msg: "Service {{ item }} vẫn đang chạy"
        success_msg: "Service {{ item }} đã dừng"
      loop: "{{ zabbix_services }}"
